apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ad45e8473a675437c98ab5b0e36869af-2d2bbf7f2ba64035.elb.us-west-2.amazonaws.com
      khttp:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: store-cluster-ip-service
                port:
                  number: 80
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: prod-api-cluster-ip-service
                port:
                  number: 5002